### ISSUE TITLE
Error in GSA analysis

### ISSUE THREAD

**Issue by rronen** [MikeJSeo/SAM#6]
Hi SAM developers,

Running GSA using the R package (GSA, v1.03) I came across an issue related to missing (NA) values.

For a minimal example of this, see the "dummy" example from the PDF docs ([here](http://cran.r-project.org/web/packages/GSA/GSA.pdf), bottom of page 4 & top of page 5). As it is the example works fine, however, introducing a single `NA` in the expression matrix, as in `x[2,2] <- NA` causes the GSA() command to fail with:

```
Error in rowMeans(x) : 'x' must be an array of at least two dimensions
```

Am I missing something basic? Or perhaps this is a version issue?

Thanks for your help!

All the best,
Roy

**Comment by MikeJSeo** [comment]
Hey Roy,

The problem is that there is an error in how GSA computes missing values at the moment. 
In the GSA code, if you look at the GSA code, there is this line.

if (sum(is.na(x)) > 0) {
            require(impute)
            x = impute.knn(x, k = knn.neighbors)
}

This should be x = impute.knn(x, k = knn.neighbors)$data 

Anyways, as a quickfix, 
you should impute the data first,  x= impute.knn(x, k = 10), then run GSA.  

Oh and to install the impute package, I think you need to install it from bioconductor.

source("http://bioconductor.org/biocLite.R")
biocLite("impute")

Mike

**Comment by rronen** [comment]
Got it. Thanks Mike! 

I'll try this and post updates here if I run into any further issues.
